## Упражнения по библиотеке Numpy

In [3]:
import numpy as np
import scipy

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [8]:
arr = np.arange(10)
mask = (3 < arr) & (arr < 8)
arr[mask] = arr[mask] * -1
print(arr)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


**2.** Заменить максимальный элемент случайного массива на 0

In [10]:
arr = np.random.randint(1,23, 10)
res = np.max(arr)

print(arr, res)

[20  9  1  4  1  2 22  9 12  9] 22


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [13]:
arr = np.random.randint(1, 30, (2,5))
result_3 = np.kron(arr[0], arr[1])
print(arr, result_3, sep='\n')

[[ 8  2 20 21 21]
 [21 22  1 23  7]]
[168 176   8 184  56  42  44   2  46  14 420 440  20 460 140 441 462  21
 483 147 441 462  21 483 147]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [152]:
# your code

**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [14]:
A = np.array([
    [1, 2, 3],
    [2, 2, 3],
    [3, 3, 3],
    [4, 2, 3],
    [5, 2, 3],
    [3, 3, 3],
    [7, 2, 3],
    [8, 2, 3],
    [8, 2, 3],
    [8, 8, 8]
])

mask = (A[:,0] == A[:,1]) & (A[:,1] == A[:,2])
A = A[~mask]
print(A)

[[1 2 3]
 [2 2 3]
 [4 2 3]
 [5 2 3]
 [7 2 3]
 [8 2 3]
 [8 2 3]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [16]:
A = np.array([
    [1, 2, 3],
    [2, 2, 3],
    [3, 3, 3],
    [4, 2, 3],
    [3, 3, 3],
    [3, 3, 3],
    [7, 2, 3],
    [8, 2, 3],
    [8, 2, 3],
    [8, 8, 8]
])
result = np.unique(A, axis=0, equal_nan=False)
print(result)

[[1 2 3]
 [2 2 3]
 [3 3 3]
 [4 2 3]
 [7 2 3]
 [8 2 3]
 [8 8 8]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [19]:
from copy import deepcopy

#7.1 without numpy
X = [[1, 0, 1, 5, 5, 7],
     [2, 0, 2, 5, 5, 7],
     [3, 0, 3, 5, 5, 7],
     [4, 4, 4, 5, 5, 7],
     [4, 4, 4, 5, 5, 7],
     [4, 4, 4, 5, 5, 7]]
new_list = deepcopy(X[:len(X[0])])
result_7_1_py = 1
for i,j in enumerate(new_list):
    if j[i] != 0:
        result_7_1_py *= j[i]
print(result_7_1_py)

#7.1 numpy
X = [[1, 0, 1, 5, 5, 7],
     [2, 0, 2, 5, 5, 7],
     [3, 0, 3, 5, 5, 7],
     [4, 4, 4, 5, 5, 7],
     [4, 4, 4, 5, 5, 7],
     [4, 4, 4, 5, 5, 7]]

main_diag = np.diag(X)
result_7_1_np = np.prod(main_diag, where=(main_diag != 0))
print(result_7_1_np)

525
525


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [21]:
#7.2 without numpy
x = [1, 2, 2, 4, 3]
y = [4, 2, 1, 2, 4]
result_7_2_py = sorted(x) == sorted(y)
print(result_7_2_py)

#7.2 with numpy
x = np.array([3, 2, 1, 2, 5])
y = np.array([4, 2, 1, 2, 3])
result_7_2_np = np.array_equal(np.sort(x), np.sort(y))
print(result_7_2_np)


False
False


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [23]:
#7.3 without numpy
x = [0, 2, 0, 3, 0, 110, 5, 7, 0, 9, 0, 1110]
arr = [x[i] for i in range(1, len(x)) if x[i-1] == 0]
print(max(arr))

#7.3 numpy
x = np.array([0, 2, 0, 3, 0, 110, 5, 7, 0, 9, 0, 1110])
mask = x[:-1] == 0
result_7_3_np = x[1:][mask]
print(max(result_7_3_np))

1110
1110


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [24]:
#7.4 without numpy
x = [2, 2, 2, 3, 3, 3, 5]
without_dupl = tuple(set(x))
result_7_4_py = [x.count(i) for i in without_dupl ]
print(without_dupl, tuple(result_7_4_py))

#7.4 numpy
x = np.array([2, 2, 2, 3, 3, 3, 5])
result_7_4_np = np.unique_counts(x)
print((result_7_4_np.values, result_7_4_np.counts))

(2, 3, 5) (3, 3, 1)
(array([2, 3, 5]), array([3, 3, 1]))


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [31]:
from scipy.spatial.distance import cdist
from scipy.spatial import distance
from functools import wraps
import time


#7.5 without numpy
A = [[1, 2, 3, 4],[5, 6, 7, 9]]
B = [0.5, 0.1, 0.3, 0.6]

def timer(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        st = time.time()
        res = func(*args, **kwargs)
        dt = time.time() - st
        print(f'Результат выполнения функции : {res}')
        print(f'Время выполнения функции {wrapper.__name__}: {dt}')
    return wrapper


@timer
def evkld_dist_python(xp:list, yp:list)->list:
    """Evklid distance by Python"""
    evkld_dist = []
    for row in xp:
        dist = [pow((i - j),2) for i, j in zip(row, yp)]
        evkld_dist.append((sum(dist))**0.5)
    return evkld_dist


#7.5 with scipy
As = np.array([[1, 2, 3, 4],[5, 6, 7, 9]])
Bs = np.array([[0.5, 0.1, 0.3, 0.6]])

@timer
def evkld_dist_scipy(xs:list, ys:list)->list:
    """Evklid distance by Spicy"""
    evklid_dist = cdist(xs, ys, metric='euclidean')
    return evklid_dist


#7.5 with numpy
An = np.array([[1, 2, 3, 4],[5, 6, 7, 9]])
Bn = np.array([[0.5, 0.1, 0.3, 0.6]])

@timer
def evkld_dist_numpy(xn:list, yn:list)->list:
    """Evklid distance by Numpy"""
    differ = xn - yn
    pow_res = np.pow(differ,2)
    evkld_dist = np.sum(pow_res, axis=1)
    return np.sqrt(evkld_dist)

#вызов 3х функций подсчёта Evklid distance
evkld_dist_python(A, B)
evkld_dist_scipy(As, Bs)
evkld_dist_numpy(An, Bn)

Результат выполнения функции : [4.765501022977542, 13.057947771376634]
Время выполнения функции evkld_dist_python: 2.2411346435546875e-05
Результат выполнения функции : [[ 4.76550102]
 [13.05794777]]
Время выполнения функции evkld_dist_scipy: 0.0008819103240966797
Результат выполнения функции : [ 4.76550102 13.05794777]
Время выполнения функции evkld_dist_numpy: 0.0001456737518310547


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [77]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [33]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [35]:
crunch = 60
average_calories = np.average(calorie_stats) - crunch
print(f'Разница со средним значением наших конкурентов и нашими хлопьями составляет {round(average_calories,1)}')

Разница со средним значением наших конкурентов и нашими хлопьями составляет 46.9


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [36]:
calorie_stats_sorted = np.sort(calorie_stats)
print(f'Отсортированные данные: {calorie_stats_sorted}')

Отсортированные данные: [ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [37]:
median_calories = np.median(calorie_stats_sorted)
print(f'Медиана по нашим данным: {median_calories}')

Медиана по нашим данным: 110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [38]:
def percent(percent: int|float)->str:
    return f'Только {percent} процента из наших конкурентов имееют {np.percentile(calorie_stats_sorted, percent)} калорий на порцию хлопьев'

print(percent(3.3))

Только 3.3 процента из наших конкурентов имееют 60.16 калорий на порцию хлопьев


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [39]:
more_calories = calorie_stats_sorted[calorie_stats_sorted > 60].size / calorie_stats_sorted.size * 100
print(more_calories)


96.1038961038961


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [40]:
calorie_std = np.std(calorie_stats_sorted)
print(calorie_std)

19.35718533390827


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [167]:
print('Я бы сказал что данные которые мы получили показывают хорошую возможность для развития '
      'CrunchieMunchies. Небольшое кол-во калорий в сравнении с конкурентами говорит о том что в еде мало жиров и '
      'сахара. Это является основой в здоровой и сбалансированной пище, как для взрослых так и для детей.')